# Generated by Django 2.2.2 on 2019-06-25 10:36

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('tage', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(max_length=256)),
                ('is_activate', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='博客类别')),
                ('number', models.IntegerField(default=1, verbose_name='分类数目')),
            ],
            options={
                'verbose_name': '博客类别',
                'verbose_name_plural': '博客类别',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(choices=[('city', '城市'), ('tag', '地标')], default='城市', max_length=32)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('plantime', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '城市地标',
                'verbose_name_plural': '城市地标',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_nums', models.IntegerField(default=0, verbose_name='博客数目')),
                ('category_nums', models.IntegerField(default=0, verbose_name='分类数目')),
                ('tag_nums', models.IntegerField(default=0, verbose_name='标签数目')),
                ('visit_nums', models.IntegerField(default=0, verbose_name='网站访问量')),
            ],
            options={
                'verbose_name': '数目统计',
                'verbose_name_plural': '数目统计',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_1', models.CharField(max_length=256)),
                ('task_2', models.CharField(max_length=256)),
                ('task_3', models.CharField(max_length=256)),
                ('task_4', models.CharField(max_length=256)),
                ('createuser', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('createuser', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=256)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '微博',
                'verbose_name_plural': '微博',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Search_submit_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_no', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('search_range', models.CharField(default='', max_length=32)),
                ('search_type', models.CharField(default='', max_length=32)),
                ('content', models.CharField(max_length=256)),
                ('current_url', models.CharField(max_length=256)),
                ('is_activate', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitetype', models.CharField(max_length=256)),
                ('sitename', models.CharField(max_length=256)),
                ('sitelink', models.CharField(max_length=256)),
                ('sitenote', models.CharField(max_length=256)),
                ('createuser', models.CharField(max_length=256)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '站点导航',
                'verbose_name_plural': '站点导航',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='站点类别')),
                ('number', models.IntegerField(default=1, verbose_name='分类数目')),
            ],
            options={
                'verbose_name': '站点类别',
                'verbose_name_plural': '站点类别',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='博客标签')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.CreateModel(
            name='TestBench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='--', max_length=999)),
                ('task', models.CharField(choices=[('miss', '漏测大全'), ('bug', '线上反馈'), ('research', '成果展示')], default='bug', max_length=32)),
                ('createuser', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '测试工作台',
                'verbose_name_plural': '测试工作台',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=256)),
                ('month', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('createuser', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('has_activate', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('linetime', models.DateTimeField()),
                ('keyword', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '大事件',
                'verbose_name_plural': '大事件',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('from_ip', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='佚名', max_length=20, verbose_name='姓名')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_activate', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='博客')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='博客类别'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
